spring:
  application:
    name: eureka2
  security:
    user:
      name: dtsaas
      password: P72iocksCDGA5MSG


server:
  port: 7001
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    status-page-url: https://www.baidu.com
  client:
    service-url:
      defaultZone: http://dtsaas:P72iocksCDGA5MSG@localhost:7000/eureka/
debug: true
